echo "Hello track!"

Hello track!

pip3 install --disable-pip-version-check -r requirements.txt

mocha --exit -R tap

1..12


#### 入力:

2

1 2

3 4

2 1

3 4

#### 標準エラー出力:

Traceback (most recent call last):

File "main.py", line 104, in <module>

main(lines)

File "main.py", line 89, in main

pre_field = lines[1:number_of_line + 1]

TypeError: can only concatenate str (not "int") to str

Command exited with non-zero status 1


not ok 1 [基本実装] Nが2である場合に正答できる

AssertionError: ステータスコードが正常(0)ではありません

at TestRunner.verifyStatusCode (/root/node_modules/codecheck/src/test_runner/testRunner.js:130:14)

at processTicksAndRejections (internal/process/task_queues.js:97:5)

at async TestRunner.postProcess (/root/node_modules/codecheck/src/test_runner/testRunner.js:105:5)

at async Context.<anonymous> (/root/node_modules/codecheck/src/test_runner/testRunner.js:95:9)


#### 入力:

3

1 2 3

4 5 6

7 8 9

2 1 3

5 4 6

8 7 9

#### 標準エラー出力:

Traceback (most recent call last):

File "main.py", line 104, in <module>

main(lines)

File "main.py", line 89, in main

pre_field = lines[1:number_of_line + 1]

TypeError: can only concatenate str (not "int") to str

Command exited with non-zero status 1


not ok 2 [基本実装] Nが3である場合に正答できる

AssertionError: ステータスコードが正常(0)ではありません

at TestRunner.verifyStatusCode (/root/node_modules/codecheck/src/test_runner/testRunner.js:130:14)

at processTicksAndRejections (internal/process/task_queues.js:97:5)

at async TestRunner.postProcess (/root/node_modules/codecheck/src/test_runner/testRunner.js:105:5)

at async Context.<anonymous> (/root/node_modules/codecheck/src/test_runner/testRunner.js:95:9)


#### 入力:

2

2 4

1 3

1 4

3 2

#### 標準エラー出力:

Traceback (most recent call last):

File "main.py", line 104, in <module>

main(lines)

File "main.py", line 89, in main

pre_field = lines[1:number_of_line + 1]

TypeError: can only concatenate str (not "int") to str

Command exited with non-zero status 1


not ok 3 [基本実装] Nが2である場合に正答できる

AssertionError: ステータスコードが正常(0)ではありません

at TestRunner.verifyStatusCode (/root/node_modules/codecheck/src/test_runner/testRunner.js:130:14)

at processTicksAndRejections (internal/process/task_queues.js:97:5)

at async TestRunner.postProcess (/root/node_modules/codecheck/src/test_runner/testRunner.js:105:5)

at async Context.<anonymous> (/root/node_modules/codecheck/src/test_runner/testRunner.js:95:9)


#### 入力:

3

9 5 1

4 6 2

8 3 7

1 9 2

5 8 4

7 6 3

#### 標準エラー出力:

Traceback (most recent call last):

File "main.py", line 104, in <module>

main(lines)

File "main.py", line 89, in main

pre_field = lines[1:number_of_line + 1]

TypeError: can only concatenate str (not "int") to str

Command exited with non-zero status 1


not ok 4 [基本実装] Nが3である場合に正答できる

AssertionError: ステータスコードが正常(0)ではありません

at TestRunner.verifyStatusCode (/root/node_modules/codecheck/src/test_runner/testRunner.js:130:14)

at processTicksAndRejections (internal/process/task_queues.js:97:5)

at async TestRunner.postProcess (/root/node_modules/codecheck/src/test_runner/testRunner.js:105:5)

at async Context.<anonymous> (/root/node_modules/codecheck/src/test_runner/testRunner.js:95:9)


#### 入力:

3

4 1 7

3 6 2

9 8 5

3 4 6

8 5 7

9 2 1

#### 標準エラー出力:

Traceback (most recent call last):

File "main.py", line 104, in <module>

main(lines)

File "main.py", line 89, in main

pre_field = lines[1:number_of_line + 1]

TypeError: can only concatenate str (not "int") to str

Command exited with non-zero status 1


not ok 5 [基本実装] Nが3である場合に正答できる

AssertionError: ステータスコードが正常(0)ではありません

at TestRunner.verifyStatusCode (/root/node_modules/codecheck/src/test_runner/testRunner.js:130:14)

at processTicksAndRejections (internal/process/task_queues.js:97:5)

at async TestRunner.postProcess (/root/node_modules/codecheck/src/test_runner/testRunner.js:105:5)

at async Context.<anonymous> (/root/node_modules/codecheck/src/test_runner/testRunner.js:95:9)


#### 入力:

3

1 9 5

4 8 2

3 7 6

2 4 9

1 3 5

6 7 8

#### 標準エラー出力:

Traceback (most recent call last):

File "main.py", line 104, in <module>

main(lines)

File "main.py", line 89, in main

pre_field = lines[1:number_of_line + 1]

TypeError: can only concatenate str (not "int") to str

Command exited with non-zero status 1


not ok 6 [基本実装] Nが3である場合に正答できる

AssertionError: ステータスコードが正常(0)ではありません

at TestRunner.verifyStatusCode (/root/node_modules/codecheck/src/test_runner/testRunner.js:130:14)

at processTicksAndRejections (internal/process/task_queues.js:97:5)

at async TestRunner.postProcess (/root/node_modules/codecheck/src/test_runner/testRunner.js:105:5)

at async Context.<anonymous> (/root/node_modules/codecheck/src/test_runner/testRunner.js:95:9)


#### 入力:

3

1 4 9

7 6 8

2 5 3

9 3 6

7 1 4

8 5 2

#### 標準エラー出力:

Traceback (most recent call last):

File "main.py", line 104, in <module>

main(lines)

File "main.py", line 89, in main

pre_field = lines[1:number_of_line + 1]

TypeError: can only concatenate str (not "int") to str

Command exited with non-zero status 1


not ok 7 [基本実装] Nが3である場合に正答できる

AssertionError: ステータスコードが正常(0)ではありません

at TestRunner.verifyStatusCode (/root/node_modules/codecheck/src/test_runner/testRunner.js:130:14)

at processTicksAndRejections (internal/process/task_queues.js:97:5)

at async TestRunner.postProcess (/root/node_modules/codecheck/src/test_runner/testRunner.js:105:5)

at async Context.<anonymous> (/root/node_modules/codecheck/src/test_runner/testRunner.js:95:9)


#### 入力:

4

16 5 15 4

13 14 9 3

1 7 12 11

2 6 8 10

12 11 7 5

6 3 16 1

13 2 14 4

8 9 15 10

#### 標準エラー出力:

Traceback (most recent call last):

File "main.py", line 104, in <module>

main(lines)

File "main.py", line 89, in main

pre_field = lines[1:number_of_line + 1]

TypeError: can only concatenate str (not "int") to str

Command exited with non-zero status 1


not ok 8 [発展実装] Nが4である場合に正答できる

AssertionError: ステータスコードが正常(0)ではありません

at TestRunner.verifyStatusCode (/root/node_modules/codecheck/src/test_runner/testRunner.js:130:14)

at processTicksAndRejections (internal/process/task_queues.js:97:5)

at async TestRunner.postProcess (/root/node_modules/codecheck/src/test_runner/testRunner.js:105:5)

at async Context.<anonymous> (/root/node_modules/codecheck/src/test_runner/testRunner.js:95:9)


#### 入力:

5

3 7 2 4 18

24 14 12 6 13

11 17 23 5 10

8 20 1 9 16

15 25 19 22 21

15 22 5 21 20

6 17 8 1 10

2 24 16 14 9

3 13 18 7 23

19 4 11 12 25

#### 標準エラー出力:

Traceback (most recent call last):

File "main.py", line 104, in <module>

main(lines)

File "main.py", line 89, in main

pre_field = lines[1:number_of_line + 1]

TypeError: can only concatenate str (not "int") to str

Command exited with non-zero status 1


not ok 9 [発展実装] Nが5である場合に正答できる

AssertionError: ステータスコードが正常(0)ではありません

at TestRunner.verifyStatusCode (/root/node_modules/codecheck/src/test_runner/testRunner.js:130:14)

at processTicksAndRejections (internal/process/task_queues.js:97:5)

at async TestRunner.postProcess (/root/node_modules/codecheck/src/test_runner/testRunner.js:105:5)

at async Context.<anonymous> (/root/node_modules/codecheck/src/test_runner/testRunner.js:95:9)


#### 入力:

4

8 13 10 6

1 3 9 2

4 16 7 14

5 15 12 11

15 13 14 5

7 4 2 1

16 6 11 10

8 9 3 12

#### 標準エラー出力:

Traceback (most recent call last):

File "main.py", line 104, in <module>

main(lines)

File "main.py", line 89, in main

pre_field = lines[1:number_of_line + 1]

TypeError: can only concatenate str (not "int") to str

Command exited with non-zero status 1


not ok 10 [発展実装] Nが4である場合に正答できる

AssertionError: ステータスコードが正常(0)ではありません

at TestRunner.verifyStatusCode (/root/node_modules/codecheck/src/test_runner/testRunner.js:130:14)

at processTicksAndRejections (internal/process/task_queues.js:97:5)

at async TestRunner.postProcess (/root/node_modules/codecheck/src/test_runner/testRunner.js:105:5)

at async Context.<anonymous> (/root/node_modules/codecheck/src/test_runner/testRunner.js:95:9)


#### 入力:

5

1 15 24 16 19

8 14 21 12 7

25 3 20 5 13

9 4 6 23 11

2 17 18 10 22

5 6 1 4 22

21 15 2 10 14

23 11 13 3 9

17 8 7 25 16

20 19 12 24 18

#### 標準エラー出力:

Traceback (most recent call last):

File "main.py", line 104, in <module>

main(lines)

File "main.py", line 89, in main

pre_field = lines[1:number_of_line + 1]

TypeError: can only concatenate str (not "int") to str

Command exited with non-zero status 1


not ok 11 [発展実装] Nが5である場合に正答できる

AssertionError: ステータスコードが正常(0)ではありません

at TestRunner.verifyStatusCode (/root/node_modules/codecheck/src/test_runner/testRunner.js:130:14)

at processTicksAndRejections (internal/process/task_queues.js:97:5)

at async TestRunner.postProcess (/root/node_modules/codecheck/src/test_runner/testRunner.js:105:5)

at async Context.<anonymous> (/root/node_modules/codecheck/src/test_runner/testRunner.js:95:9)


#### 入力:

30

631 629 79 409 553 649 135 739 362 678 356 304 489 244 147 66 410 723 636 112 280 43 444 792 686 69 593 520 373 353

275 200 815 532 667 731 572 694 403 546 21 825 758 598 495 768 637 481 806 882 314 217 582 783 318 762 660 33 570 70

334 751 547 607 573 805 384 406 491 167 321 392 528 594 657 207 ...

#### 標準エラー出力:

Traceback (most recent call last):

File "main.py", line 104, in <module>

main(lines)

File "main.py", line 89, in main

pre_field = lines[1:number_of_line + 1]

TypeError: can only concatenate str (not "int") to str

Command exited with non-zero status 1


not ok 12 [発展実装] Nが30である場合に正答できる

AssertionError: ステータスコードが正常(0)ではありません

at TestRunner.verifyStatusCode (/root/node_modules/codecheck/src/test_runner/testRunner.js:130:14)

at processTicksAndRejections (internal/process/task_queues.js:97:5)

at async TestRunner.postProcess (/root/node_modules/codecheck/src/test_runner/testRunner.js:105:5)

at async Context.<anonymous> (/root/node_modules/codecheck/src/test_runner/testRunner.js:95:9)

# tests 12

# pass 0

# fail 12

exit_code = 12, reason = DONE

pip3 install --disable-pip-version-check -r requirements.txt

mocha --exit -R tap

1..12


#### 入力:

2

1 2

3 4

2 1

3 4

#### 標準エラー出力:

Traceback (most recent call last):

File "main.py", line 104, in <module>

main(lines)

File "main.py", line 89, in main

pre_field = lines[1:number_of_line + 1]

TypeError: can only concatenate str (not "int") to str

Command exited with non-zero status 1


not ok 1 [基本実装] Nが2である場合に正答できる

AssertionError: ステータスコードが正常(0)ではありません

at TestRunner.verifyStatusCode (/root/node_modules/codecheck/src/test_runner/testRunner.js:130:14)

at processTicksAndRejections (internal/process/task_queues.js:97:5)

at async TestRunner.postProcess (/root/node_modules/codecheck/src/test_runner/testRunner.js:105:5)

at async Context.<anonymous> (/root/node_modules/codecheck/src/test_runner/testRunner.js:95:9)

